In [1]:
import numpy as np

In [2]:
# 1. 通过特定函数, 生成一个16个元素numpy数组, 这些元素为0-1间的随机数
random_array = np.random.rand(16)
print("原始随机数组 (1x16):\n", random_array)

# 2. 数组进行变形为4x4的数组
reshaped_array = random_array.reshape(4, 4)
print("\n变形后的数组 (4x4):\n", reshaped_array)

# 3. 转置数组
transposed_array = reshaped_array.T
print("\n转置后的数组 (4x4):\n", transposed_array)

# 4. 创建一个4x4全一数组
ones_array = np.ones((4, 4))
print("\n全一数组 (4x4):\n", ones_array)

# 5. 分别进行算术加, 算数减, 算术乘, 以及点积
addition_result = transposed_array + ones_array
print("\n算术加结果 (4x4):\n", addition_result)

subtraction_result = transposed_array - ones_array
print("\n算术减结果 (4x4):\n", subtraction_result)

multiplication_result = transposed_array * ones_array
print("\n算术乘结果 (4x4):\n", multiplication_result)

dot_product_result = np.dot(transposed_array, ones_array)
print("\n点积结果 (4x4):\n", dot_product_result)

原始随机数组 (1x16):
 [0.74372627 0.60142978 0.25787357 0.07786607 0.93867109 0.87346353
 0.43526594 0.08307946 0.04913006 0.90634058 0.53845428 0.69641176
 0.16699457 0.27922529 0.90030892 0.18056011]

变形后的数组 (4x4):
 [[0.74372627 0.60142978 0.25787357 0.07786607]
 [0.93867109 0.87346353 0.43526594 0.08307946]
 [0.04913006 0.90634058 0.53845428 0.69641176]
 [0.16699457 0.27922529 0.90030892 0.18056011]]

转置后的数组 (4x4):
 [[0.74372627 0.93867109 0.04913006 0.16699457]
 [0.60142978 0.87346353 0.90634058 0.27922529]
 [0.25787357 0.43526594 0.53845428 0.90030892]
 [0.07786607 0.08307946 0.69641176 0.18056011]]

全一数组 (4x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

算术加结果 (4x4):
 [[1.74372627 1.93867109 1.04913006 1.16699457]
 [1.60142978 1.87346353 1.90634058 1.27922529]
 [1.25787357 1.43526594 1.53845428 1.90030892]
 [1.07786607 1.08307946 1.69641176 1.18056011]]

算术减结果 (4x4):
 [[-0.25627373 -0.06132891 -0.95086994 -0.83300543]
 [-0.39857022 -0.12653647 -0.09365942 -0.72077471

In [3]:
# 6. 最后结果转为一维数组
flattened_addition = addition_result.flatten()
flattened_subtraction = subtraction_result.flatten()
flattened_multiplication = multiplication_result.flatten()
flattened_dot_product = dot_product_result.flatten()

print("\n算术加结果 (一维数组):\n", flattened_addition)
print("\n算术减结果 (一维数组):\n", flattened_subtraction)
print("\n算术乘结果 (一维数组):\n", flattened_multiplication)
print("\n点积结果 (一维数组):\n", flattened_dot_product)


算术加结果 (一维数组):
 [1.74372627 1.93867109 1.04913006 1.16699457 1.60142978 1.87346353
 1.90634058 1.27922529 1.25787357 1.43526594 1.53845428 1.90030892
 1.07786607 1.08307946 1.69641176 1.18056011]

算术减结果 (一维数组):
 [-0.25627373 -0.06132891 -0.95086994 -0.83300543 -0.39857022 -0.12653647
 -0.09365942 -0.72077471 -0.74212643 -0.56473406 -0.46154572 -0.09969108
 -0.92213393 -0.91692054 -0.30358824 -0.81943989]

算术乘结果 (一维数组):
 [0.74372627 0.93867109 0.04913006 0.16699457 0.60142978 0.87346353
 0.90634058 0.27922529 0.25787357 0.43526594 0.53845428 0.90030892
 0.07786607 0.08307946 0.69641176 0.18056011]

点积结果 (一维数组):
 [1.89852199 1.89852199 1.89852199 1.89852199 2.66045919 2.66045919
 2.66045919 2.66045919 2.13190272 2.13190272 2.13190272 2.13190272
 1.03791739 1.03791739 1.03791739 1.03791739]
